apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
      - name: mern-backend
        image: udaybadola/mern-backend:latest2
        ports:
        - containerPort: 5050
        env:
        - name: MONGO_URI
          value: mongodb://mongodb:27017/mydatabase  # Ensure this matches your MongoDB service name
---
apiVersion: v1
kind: Service
metadata:
  name: mern-backend-service
spec:
  selector:
    app: mern-backend
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: LoadBalancer  # This exposes the service externally
